    import React from 'react';
    import Header from '../components/Header';

    const Jargon = () => {
        return (
            <div className="bg-black min-h-screen w-full text-white flex flex-col justify-center items-center">
                <Header />
                <div class="px-4 py-8 max-w-screen-md bg-white text-black">
        <h1 class="text-xl font-bold mb-4">MVP (Minimum Viable Product):</h1>
        <p>The most basic version of a product that allows a startup to collect the maximum amount of validated learning about customers with the least effort.</p>
        
        <h1 class="text-xl font-bold mt-8 mb-4">TG (Target Group):</h1>
        <p>The specific demographic or audience segment that a product or service is intended to serve or appeal to.</p>
        
        <h1 class="text-xl font-bold mt-8 mb-4">TAM (Total Addressable Market):</h1>
        <p>The total market demand for a product or service, representing the maximum revenue opportunity available to a startup.</p>
        
        <h1 class="text-xl font-bold mt-8 mb-4">SAM (Serviceable Addressable Market):</h1>
        <p>The portion of the total addressable market that a startup can realistically target and serve with its resources and capabilities.</p>
        
        <h1 class="text-xl font-bold mt-8 mb-4">SOM (Serviceable Obtainable Market):</h1>
        <p>The portion of the serviceable addressable market that a startup can effectively capture and acquire as customers.</p>
        
        <h1 class="text-xl font-bold mt-8 mb-4">GTM (Go-To Market):</h1>
        <p>The strategy and process a startup uses to bring its product or service to market and acquire customers.</p>
        
        <h1 class="text-xl font-bold mt-8 mb-4">PMF (Product Market Fit):</h1>
        <p>The stage at which a startup has developed a product that meets the needs and demands of its target market, resulting in strong customer satisfaction and demand.</p>
        
        <h1 class="text-xl font-bold mt-8 mb-4">CAC (Customer Acquisition Cost):</h1>
        <p>The cost associated with acquiring a new customer, including marketing and sales expenses.</p>
        
        <h1 class="text-xl font-bold mt-8 mb-4">ROAS (Return On Ad Spend):</h1>
        <p>A metric used to measure the effectiveness of advertising campaigns by comparing the revenue generated to the cost of the advertising.</p>
        
        <h1 class="text-xl font-bold mt-8 mb-4">MRR (Monthly Recurring Revenue):</h1>
        <p>The predictable and repeatable revenue generated by a subscription-based business model on a monthly basis.</p>
        
        <h1 class="text-xl font-bold mt-8 mb-4">CMGR (Compound Monthly Growth Rate):</h1>
        <p>The average monthly growth rate of a startup's key metrics, calculated on a compounded basis over a specific period.</p>
        
        <h1 class="text-xl font-bold mt-8 mb-4">GUC (Gross User Churn):</h1>
        <p>The rate at which customers or users discontinue their subscription or stop using a product or service, without factoring in new additions or upgrades.</p>
        
        <h1 class="text-xl font-bold mt-8 mb-4">CCC (Customer Carrying Cost):</h1>
        <p>The total cost incurred by a startup to acquire, serve, and retain customers over a specific period.</p>
        
        <h1 class="text-xl font-bold mt-8 mb-4">MIS (Management Information System):</h1>
        <p>A system used by startups to collect, process, and present data and information to support decision-making and management activities.</p>
        <h1 class="text-4xl font-bold mb-4 mt-8 text-center">Financial metrics</h1>
        <ul>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">GMV (Gross Merchandise Value):</h2>
                <p>The total value of merchandise sold through a platform or marketplace, before deducting any discounts, returns, or allowances.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">LTV (Lifetime Value of The Customer):</h2>
                <p>The predicted net profit attributed to the entire future relationship with a customer, taking into account their purchasing behavior, retention, and potential referrals.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">CM (Contribution Margin):</h2>
                <p>The measure of the profitability of a product or service, calculated as the difference between total revenue and variable costs, expressed as a percentage of revenue.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">GM (Gross Margin):</h2>
                <p>The percentage difference between the revenue generated from the sale of a product or service and the cost of goods sold, representing the profitability of each unit sold after accounting for direct production costs.</p>
            </li>
        </ul>

        <h1 class="text-4xl font-bold mt-8 mb-4 text-center">Operating and Cohort metrics</h1>
        <ul>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">DAU (Daily Active User):</h2>
                <p>The number of unique users who engage with a product or service within a single day.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">MAU (Monthly Active Users):</h2>
                <p>The number of unique users who engage with a product or service within a calendar month.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">WAU (Weekly Active Users):</h2>
                <p>The number of unique users who engage with a product or service within a week.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">ARR (Annual Run Rate):</h2>
                <p>The projected annual revenue based on the current run rate, often used to estimate a company's future revenue performance.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">FY (Financial Year/Fiscal Year):</h2>
                <p>A period used for accounting and financial reporting purposes, typically spanning 12 consecutive months.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">NPS (Net Promoter Score):</h2>
                <p>A metric used to measure customer satisfaction and loyalty based on the likelihood of customers to recommend a product or service to others.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">CAGR (Compounded Annual Growth Rate):</h2>
                <p>The rate of return that would be required for an investment to grow from its initial value to its ending value over a specified period, assuming the profits were reinvested at the end of each period and compounded annually.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">EBITDA (Earnings Before Interest, Tax, Depreciation and Amortization):</h2>
                <p>A measure of a company's operating performance, calculated as its revenue minus expenses (excluding interest, taxes, depreciation, and amortization).</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">P&L Statement (Profit and Loss Statement):</h2>
                <p>A financial statement that summarizes the revenues, costs, and expenses incurred by a business during a specific period, typically quarterly or annually, resulting in the calculation of net income or loss.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">COGS (Cost Of Goods Sold):</h2>
                <p>The direct costs associated with producing or acquiring the goods sold by a company, including materials, labor, and manufacturing overhead.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">CM (Contribution Margin):</h2>
                <p>The difference between total revenue and variable costs, representing the portion of sales revenue that contributes to covering fixed costs and generating profit.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">CFF (Cash Flow from Financing Activities):</h2>
                <p>The net cash inflow or outflow resulting from activities related to the financing of a company, including issuing or repurchasing stock, and borrowing or repaying debt.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">CFI (Cash Flow from Investing Activities):</h2>
                <p>The net cash inflow or outflow resulting from activities related to the acquisition or disposal of long-term assets and investments, such as property, plant, and equipment.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">(D/E) Ratio (Debt to Equity Ratio):</h2>
                <p>A financial ratio that compares a company's total debt to its total equity, indicating the proportion of financing provided by debt relative to equity.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">ROE (Return On Equity):</h2>
                <p>A measure of a company's profitability relative to shareholders' equity, calculated as net income divided by average shareholders' equity.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">ROCE (Return On Capital Employed):</h2>
                <p>A measure of a company's profitability and efficiency in utilizing its capital employed in generating profits, calculated as EBIT divided by capital employed.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">ROA (Return On Assets):</h2>
                <p>A measure of a company's profitability relative to its total assets, calculated as net income divided by average total assets.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">R&D (Research and Development):</h2>
                <p>Activities undertaken by a company to innovate, improve existing products or processes, and develop new technologies or products.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">ESOP (Employee Stock Ownership Plan):</h2>
                <p>A program that allows employees to acquire ownership in the company                compensation granted to employees, entitling them to receive company stock at a future date, subject to certain conditions and restrictions, typically vesting over time.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">SAR (Stock Appreciation Rights):</h2>
                <p>A type of equity compensation that entitles the recipient to receive the appreciation in the value of a specified number of company shares over a predetermined period, without actually transferring ownership of the shares.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">EGM (Extraordinary General Meeting):</h2>
                <p>A meeting of shareholders convened by a company to discuss and vote on important matters that require their approval, such as major corporate transactions, changes to the company's charter, or other significant events.</p>
            </li>
        </ul>
        <h1 class="text-4xl font-bold mb-4 mt-8 text-center">Fundraising</h1>
        <ul>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">HNI’s (High Net worth Individuals):</h2>
                <p>Individuals with significant wealth and assets, often targeted by startups and investment firms for fundraising, investment opportunities, or high-value products and services.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">DCF (Discounted Cash Flow):</h2>
                <p>A valuation method used to estimate the value of an investment or company by discounting its expected future cash flows to their present value, taking into account the time value of money.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">AOV (Average Order Value):</h2>
                <p>The average monetary value of orders or transactions placed by customers with a company over a specific period, used to evaluate customer purchasing behavior and revenue generation.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">CCPS (Compulsorily Convertible Preference Shares):</h2>
                <p>A type of equity security issued by a company that carries certain preferential rights, such as priority in dividend payments, with an obligation to convert into equity shares at a future date or event.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">CN (Convertible Note):</h2>
                <p>A form of debt instrument issued by startups to investors, typically with a maturity date and an option to convert the debt into equity shares at a later financing round or milestone event.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">CCDS (Compulsorily Convertible Debenture Shares):</h2>
                <p>Debt securities issued by a company that are convertible into equity shares at a predetermined conversion price or event, providing investors with the option to participate in the company's equity upside.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">OCD (Optionally Convertible Debenture):</h2>
                <p>Debt securities issued by a company that may be converted into equity shares at the discretion of the holder, typically based on predetermined terms and conditions.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">OCRPS (Optionally Convertible Redeemable Preference Shares):</h2>
                <p>Preference shares issued by a company that may be optionally converted into equity shares or redeemed for cash at the discretion of the issuer, providing flexibility to both the company and investors.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">SAFE (Simple Agreement for Future Equity):</h2>
                <p>A financial instrument used in early-stage startup fundraising, allowing investors to purchase equity in a company at a future financing round or event, without determining the valuation at the time of investment.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">CSOP’s (Community Stock Options):</h2>
                <p>Stock option plans designed for community-driven organizations or platforms, allowing members or contributors to receive equity-based incentives for their participation and contributions.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">LLP (Limited Liability Partnership):</h2>
                <p>A legal business structure that combines the benefits of a partnership and a corporation, providing limited liability protection to its partners while allowing flexibility in management and taxation.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">OPC (One Person Company):</h2>
                <p>A type of business entity that allows a single individual to establish and operate a company with limited liability, providing legal protection for personal assets while enabling sole ownership and management.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">IP (Intellectual Property):</h2>
                <p>Legal rights associated with intangible assets created through intellectual efforts, including patents, trademarks, copyrights, and trade secrets, providing exclusive rights to their owners for commercial exploitation.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">MOA (Memorandum Of Association):</h2>
                <p>A legal document that outlines the constitution and objectives of a company, including its name, registered office, business activities, and details of its shareholders and directors.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">AOA (Articles Of Association):</h2>
                <p>A legal document that outlines the internal rules, regulations, and procedures governing the management and operation of a company, complementing its Memorandum of Association.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">CFA (Co-Founder’s Agreement):</h2>
                <p>A legal document that establishes the rights                , responsibilities, and obligations of co-founders of a startup, addressing key issues such as ownership, roles, decision-making, and dispute resolution.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">SPA (Share Purchase Agreement):</h2>
                <p>A legal contract that outlines the terms and conditions of the sale and purchase of shares in a company, including the purchase price, payment terms, warranties, and representations of the parties involved.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">SSA (Share Subscription Agreement):</h2>
                <p>A legal contract between a company and an investor outlining the terms and conditions under which the investor agrees to subscribe for new shares issued by the company, including the subscription price, number of shares, and payment terms.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">SHA (Share Holder’s Agreement):</h2>
                <p>A legal contract that governs the relationship between shareholders of a company, addressing matters such as ownership rights, management structure, voting rights, transfer restrictions, and dispute resolution mechanisms.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">RUV (Roll Up Precedent):</h2>
                <p>A template or model used as a reference or starting point for creating legal documents, agreements, or contracts, often tailored to suit specific transactions or circumstances.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">CS (Conditions Subsequent):</h2>
                <p>Conditions or events that must occur after the execution of a contract or agreement, typically to trigger certain rights, obligations, or consequences for the parties involved.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">FDD (Financial Due Diligence):</h2>
                <p>The process of evaluating the financial health, performance, and viability of a company or investment opportunity, typically conducted by investors or acquirers before making investment decisions.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">LDD (Legal Due Diligence):</h2>
                <p>The process of assessing the legal risks, obligations, and compliance issues associated with a company or investment opportunity, often conducted as part of mergers, acquisitions, or investments.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">TDD (Technical Due Diligence):</h2>
                <p>The process of evaluating the technical aspects, infrastructure, and capabilities of a company, project, or asset, typically conducted to assess its technological viability and scalability.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">ESG (Environment, Social and Governance):</h2>
                <p>A framework used to evaluate and measure the environmental, social, and governance practices and performance of companies, guiding investors and stakeholders in assessing sustainability and ethical impact.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">GST (Goods and Service Tax):</h2>
                <p>A value-added tax levied on the supply of goods and services in India, replacing multiple indirect taxes and streamlining the taxation system.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">IGST (Integrated Goods and Service Tax):</h2>
                <p>A component of the Goods and Service Tax (GST) system in India that applies to interstate transactions of goods and services, collected by the central government and distributed to the states.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">TDS (Tax Deduction Source):</h2>
                <p>A system in India that requires individuals or entities making certain payments to deduct tax at source and remit it to the government, ensuring tax compliance and revenue collection.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">TCS (Tac Collection at Source):</h2>
                <p>A tax collection mechanism in India that requires sellers to collect tax at source on specified transactions, such as the sale of goods, and remit it to the government.</p>
            </li>
            <li>
                <h2 class="text-xl font-bold mt-8 mb-4">KPI (Key Performance Indication):</h2>
                <p>Specific measurable metrics used to evaluate the performance and effectiveness of a business, project, or individual, typically aligned with strategic goals and objectives.</p>
            </li>
        </ul>

    </div>
    </div>
        );
    }

    export default Jargon;
